INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('apple', 'りんご', 'She ate an apple.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('run', '走る', 'He likes to run every morning.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('book', '本', 'I borrowed a book from the library.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('water', '水', 'Drink plenty of water every day.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('write', '書く', 'She writes in her diary daily.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('happy', '幸せな', 'They are very happy together.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('house', '家', 'We live in a big house.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('school', '学校', 'The school is closed today.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('car', '車', 'He bought a new car.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('eat', '食べる', 'They eat lunch at noon.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('cat', '猫', 'The cat is sleeping.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('play', '遊ぶ', 'Children play in the park.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('phone', '電話', 'She answered the phone.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('run', '走る', 'He runs very fast.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('dog', '犬', 'The dog barks loudly.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('read', '読む', 'I read a book before bed.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('drink', '飲む', 'They drink coffee every morning.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('teacher', '先生', 'The teacher explains the lesson.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('computer', 'コンピューター', 'He uses a computer for work.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('music', '音楽', 'She listens to music.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('movie', '映画', 'We watched a movie last night.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('food', '食べ物', 'The food tastes delicious.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('bicycle', '自転車', 'He rides a bicycle to school.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('travel', '旅行する', 'They travel to different countries.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('garden', '庭', 'The garden is full of flowers.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('baby', '赤ちゃん', 'The baby is sleeping.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('swim', '泳ぐ', 'They swim in the pool.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('sky', '空', 'The sky is clear today.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('train', '電車', 'He takes the train to work.');
INSERT INTO VOCABULARY(NAME, MEAN, EXAMPLE) VALUES('breakfast', '朝食', 'They have breakfast together.');
